
cp _base/webapp/modulos/appministra/models/ventas.php appmincomerv/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php botonyagujeta/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php buenprovecho/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php casamusa/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php casamusa_demo/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php cats/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php chilessecosjr/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php discocats_demo/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php distribuidoralua/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php distribuidoralua_demo/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php echologica/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php echologica_demo/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php foodwareventas/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php furterhotdogs/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php furterhotdogs_demo/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php mariacostilla/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php mariacostilla_demo/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php odepa/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php odepa_demo/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php randazzo/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php randazzo_demo/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php rockshotcafe/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php rockshotcafe_demo/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php sandaliasprincess/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php sandaliasprincess_demo/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php servicopy/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php specialized/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php tacoselcharly/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php thedwich/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php thedwich_demo/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php tinastecnospa/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php tinastecnospa_demo/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php zapateriamonarca/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php zapmonarca_demo/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php crossdepot/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php crossdepot_demo/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php bp/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php bp_demo/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php lacteosmamalupita/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php lacteosmamalupita_demo/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php soya/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php simplythai/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php proveedoracomercial/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php montparnasse/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php lapreferida/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php honorarios/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php elancla/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php edr/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php climdent/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php bistrom/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php victorplozat/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php chololo/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php nmwadmin/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php deia/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php carnesasadas_demo/webapp/modulos/appministra/models/ventas.php
cp _base/webapp/modulos/appministra/models/ventas.php carnesasadas/webapp/modulos/appministra/models/ventas.php

cp _base/webapp/modulos/appministra/controllers/compras.php appmincomerv/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php botonyagujeta/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php buenprovecho/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php casamusa/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php casamusa_demo/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php cats/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php chilessecosjr/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php discocats_demo/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php distribuidoralua/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php distribuidoralua_demo/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php echologica/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php echologica_demo/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php foodwareventas/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php furterhotdogs/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php furterhotdogs_demo/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php mariacostilla/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php mariacostilla_demo/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php odepa/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php odepa_demo/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php randazzo/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php randazzo_demo/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php rockshotcafe/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php rockshotcafe_demo/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php sandaliasprincess/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php sandaliasprincess_demo/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php servicopy/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php specialized/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php tacoselcharly/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php thedwich/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php thedwich_demo/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php tinastecnospa/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php tinastecnospa_demo/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php zapateriamonarca/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php zapmonarca_demo/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php crossdepot/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php crossdepot_demo/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php bp/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php bp_demo/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php lacteosmamalupita/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php lacteosmamalupita_demo/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php soya/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php simplythai/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php proveedoracomercial/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php montparnasse/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php lapreferida/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php honorarios/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php elancla/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php edr/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php climdent/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php bistrom/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php victorplozat/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php chololo/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php nmwadmin/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php deia/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php carnesasadas_demo/webapp/modulos/appministra/controllers/compras.php
cp _base/webapp/modulos/appministra/controllers/compras.php carnesasadas/webapp/modulos/appministra/controllers/compras.php

echo "Fin"
